server:
    port: 8050

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Back-Microservicios-Hospital/Back-Hospital-Configuration.git
